version: 2

models:
  - name: gold_customer_revenue
    description: "Total revenue aggregated per customer"
    columns:
      - name: customer_id
        tests:
          - not_null
          - unique
      - name: total_revenue_usd
        tests:
          - not_null
      - name: total_revenue_inr
        tests:
          - not_null

  - name: gold_orders
    description: "Incremental orders table from silver layer"
    columns:
      - name: order_id
        tests:
          - not_null
          - unique